### ISSUE TITLE
When sync'ing dashboards between instance A and instance B, if the dashboard title changes, gzr creates a new dashboard rather than changing the title on instance B

### ISSUE THREAD

**Issue by drewgillson** [deangelo-llooker/gzr#23] opened 2019-02-01 21:43 UTC
Please see https://github.com/deangelo-llooker/gzr/blob/master/lib/gzr/commands/dashboard/import.rb#L92. If the title on instance A changes, when sync'ing to instance B, the title is different so `existing_dashboard` gets set to false. As a result the else condition on line 120 is entered, even if the slugs are identical.

**Comment by deangelo-llooker** [comment] 2019-02-04 01:35
This is the expected behavior right now. Dashboards are matched on name/title, not slug. If you want to update a dashboard whose name/title has changed, the best action at the moment is to delete it and recreate.

I can change the behavior, but we need to be sure it is the "right" thing to do. Let me talk to engineering about the slugs and the likelihood of an accidental collision.

**Comment by ebear** [comment] 2019-02-05 01:05
Hey @deangelo-llooker I think that this is the behavior we want. So in this new world if we find a matching slug but the titles don't match we'd want to update the title on the existing dashboard. The chances of accidental collision should be extremely low, that's why we are using these slugs.
I'm talked to Delaney and he says we'd be ready to make this switch whenever you are. I'd also like to help in anyway I can, so just let me know if you want to set up a meeting or something!

**Comment by deangelo-llooker** [comment] 2019-02-06 13:18
OK I should be able to work on this today. Look for a new release late today or sometime tomorrow.

**Comment by timmcanty** [comment] 2019-02-08 20:02
We have concerns with this change, as we are relying on the title match in order to handle some problematic situations.

The number one situation is when a dashboard is deleted in Instance B. If you try to import a dashboard in Instance A whose slug matches a deleted dashboard in Instance B, the import will fail.

We currently rectify this problem by copying the dashboard in Instance A (altering the slug), while keeping the same title. If we had to rely on the slug to be the same, we would have to delete any colliding target dashboards that are no colliding.  (The target dashboard was made in Instance B by copying the dashboard before deleting it).

I am worried that removing the title matching will stop workarounds when we have a slug collision with a deleted dashboard. 

We would be fine to use this change if our initial issue (slug collisions with deleted dashboards) was properly handled.

**Comment by ebear** [comment] 2019-02-08 21:07
Hey @timmcanty that's a very reasonable concern. I wanted to let you know the issue with slugs persisting after a dashboard has been deleted is fixed in Looker 6.4. That said I believe you can use previous versions of gzr in the meantime (@deangelo-llooker correct me if I'm wrong).

**Comment by timmcanty** [comment] 2019-02-08 21:21
Would that fix also resolve previously deleted dashboards? I encountered a repro of the described issue today where the dashboard in instance B was deleted on 2/4/19. Not sure when Looker 6.4 was released, but I personally verified a collision like the one I described happening today.

**Comment by ebear** [comment] 2019-02-08 21:46
Yes indeed, part of the fix involved going in and cleaning up any lingering slugs that were associated with previously deleted dashboards.

Looker 6.4 became available a little less than a month ago, that said I do not know what release schedule your Looker instance is on so it's entirely possible it has not been upgraded yet.

Also you may already know this, but Looker makes a distinction between moving a dashboard to the trash and actually deleting it. Dashboards in the trash can be reinstated at any time, and so they reserve their slugs until fully deleted. It's only when the dashboard is fully deleted from the trash space (either with a DELETE api call, or through the trash space's UI) that the slug will be freed up again. This isn't obvious so I just wanted to make sure it was not part of the problem.

**Comment by timmcanty** [comment] 2019-02-08 21:58
Just confirmed that the issue is resolved when hard deleting dashboards. I wish Gazer/Looker API were able to surface this slug collision in a more graceful way. It is very hard to determine the the source of the failure without digging deep into the gazer source code to debug.

**Closed** 2019-02-13 16:02 UTC

**Comment by HPNoha** [comment] 2019-06-13 20:40
I think there is still one case where there is a match by title? Here is the use case:
1. Accidentally import dashboard to space 1 (oops I reallly wanted it to be in space 2)
2. Import the same dashboard to space 2 (it creates it with a new id)
3. Update the dashboard on the first instance and re-import: works successfully on both space 1 and 2
4. Update the dashboard's title and re-import: re-imported successfully on space 1 BUT creates a new dashboard under space 2
